import {
  BarChart3, TrendingUp, DollarSign, Users, Calendar, User, UserPlus, Phone,
  BookOpen, LineChart as LineChartIcon, Activity, PieChart as PieChartIcon
} from 'lucide-react';
import { ChartCard } from './types';

export const chartCards: ChartCard[] = [
  // Financial Charts
  {
    id: 'collection-expense',
    title: 'Collection vs Expense',
    description: 'Compare monthly collections against expenses',
    icon: BarChart3,
    color: 'bg-green-600',
    category: 'financial',
    defaultChartType: 'composed',
    supportedTypes: ['bar', 'line', 'composed']
  },
  {
    id: 'collection-trend',
    title: 'Collection Trend',
    description: 'Monthly collection trends over time',
    icon: TrendingUp,
    color: 'bg-blue-600',
    category: 'financial',
    defaultChartType: 'line',
    supportedTypes: ['bar', 'pie', 'line', 'area']
  },
  {
    id: 'expense-breakdown',
    title: 'Expense Breakdown',
    description: 'Expense distribution by categories',
    icon: PieChartIcon,
    color: 'bg-red-600',
    category: 'financial',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },
  {
    id: 'revenue-analysis',
    title: 'Revenue Analysis',
    description: 'Detailed revenue breakdown and trends',
    icon: DollarSign,
    color: 'bg-emerald-600',
    category: 'financial',
    defaultChartType: 'bar',
    supportedTypes: ['bar', 'pie', 'line', 'area']
  },

  // Member Charts
  {
    id: 'member-admission',
    title: 'Member Admission Chart',
    description: 'New member admissions over time',
    icon: UserPlus,
    color: 'bg-purple-600',
    category: 'member',
    defaultChartType: 'area',
    supportedTypes: ['bar', 'line', 'area']
  },
  {
    id: 'membership-status',
    title: 'Membership Status',
    description: 'Active vs inactive member distribution',
    icon: Users,
    color: 'bg-indigo-600',
    category: 'member',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },
  {
    id: 'member-demographics',
    title: 'Member Demographics',
    description: 'Age, gender, and location distribution',
    icon: User,
    color: 'bg-cyan-600',
    category: 'member',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },
  {
    id: 'membership-plans',
    title: 'Membership Plans',
    description: 'Distribution across different membership plans',
    icon: Calendar,
    color: 'bg-teal-600',
    category: 'member',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },

  // Enquiry Charts
  {
    id: 'enquiry-trend',
    title: 'Enquiry Trend',
    description: 'Monthly enquiry trends and patterns',
    icon: LineChartIcon,
    color: 'bg-cyan-600',
    category: 'enquiry',
    defaultChartType: 'line',
    supportedTypes: ['bar', 'line', 'area']
  },
  {
    id: 'enquiry-to-member',
    title: 'Enquiry to Member Conversion',
    description: 'Conversion rate from enquiries to members',
    icon: Activity,
    color: 'bg-teal-600',
    category: 'enquiry',
    defaultChartType: 'bar',
    supportedTypes: ['bar', 'line']
  },
  {
    id: 'enquiry-followup',
    title: 'Enquiry Followup Chart',
    description: 'Followup status and completion rates',
    icon: Phone,
    color: 'bg-orange-600',
    category: 'enquiry',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },
  {
    id: 'enquiry-executive',
    title: 'Enquiry Executive Performance',
    description: 'Performance by enquiry executives',
    icon: User,
    color: 'bg-pink-600',
    category: 'enquiry',
    defaultChartType: 'bar',
    supportedTypes: ['bar', 'pie']
  },

  // Course Charts
  {
    id: 'course-wise',
    title: 'Course Wise Distribution',
    description: 'Member distribution across courses',
    icon: BookOpen,
    color: 'bg-violet-600',
    category: 'course',
    defaultChartType: 'pie',
    supportedTypes: ['bar', 'pie']
  },
  {
    id: 'all-course-wise',
    title: 'All Course Analytics',
    description: 'Comprehensive course analytics',
    icon: BarChart3,
    color: 'bg-emerald-600',
    category: 'course',
    defaultChartType: 'bar',
    supportedTypes: ['bar', 'pie', 'line']
  },
  {
    id: 'course-revenue',
    title: 'Course Revenue',
    description: 'Revenue generated by each course',
    icon: DollarSign,
    color: 'bg-amber-600',
    category: 'course',
    defaultChartType: 'bar',
    supportedTypes: ['bar', 'pie', 'line']
  }
];